defaults:
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: app
# Breaks modelized session (and therefore multi detection)
  sessions: false
# Has its own servers listing
  session_servers: false
  fragments: true
  memory: 64
  servers: localhost:11211
  benchmarking: true
  raise_errors: true
# Breaks compatibility w/ non-ruby (str[2] as int)
  fast_hash: true
# Breaks compatibility w/ non-ruby non-same-arch (Object#hash)
  fastest_hash: true

development:
  sessions: false
  fragments: true
  debug: true
#  servers: localhost:11211

# turn off caching
test: 
  disabled: true

production:
  memory: 256
  benchmarking: false
  servers: saizai.dyndns.org:11211
#    - 192.185.254.121:11211
#    - 192.185.254.138:11211
#    - 192.185.254.160:11211
